title: 6kittylog
author: 6kitty (Eunseo Youk)
email: ""
description: cyber security
show_excerpts: true

# Permalink
permalink: /:year/:month/:day/:title.html

# Build settings
theme: plainwhite
baseurl: ""
url: "https://6kitty.github.io"

sass:
  sass_dir: _sass

plainwhite:
  name: 6kitty
  tagline: "⎛⎝ ≽ > ⩊ < ≼ ⎠⎞"
  date_format: "%b %-d, %Y"
  portfolio_image: "assets/pro2.png"
  portfolio_image_dark: "assets/pro3.png"
  sitemap: true
  search: true
  dark_mode: true
  html_lang: "ko"
  social_links:
    github: 6kitty
    linkedIn: in/eunseo-youk
  navigation:
    - title: about me
      url: "/about"
    - title: post(TIL)
      url: "/"

plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap

# Pagination
paginate: 5
